module.exports = [
  {
    name: "Abdirizak Aden Mohamed",
    bio: `<p>Abdirizak Aden Mohamed is the sixth born of 12 children. He was born in Ethiopia where he lived until nine. His family lived in a rural area of the Warder region in Ethiopia where they reared small livestock. At one knight, he fled from his home country when a war, later days said to be between the government of Ethiopia and the so-called ONLF group, has suddenly broken out.  Every member of the family had to flee for his/her dear life, for there was no time to plan or regroup to escape. There is no information up to date about the livestock, perhaps were collected by either of the group. After some days of looking for each other, the family was able to reunite.</p>

    <p>They started their journey for a better life which led them to the Dadaab refugee camp and later taken to Kakuma refugee camp by UNHCR, The United Refugee Agency. He has been enrolled in that time’s Somali Bantu Primary School, and then to a newly built Lokitaung primary school. He later went to Vision secondary school. He has been in Kakuma for twelve years. He has volunteered teaching at Vision secondary school before moving to Greenlight secondary school before he was enrolled in Elimisha Kakuma.</p>

    <p>Aden inspires to pursue Computer and Electrical Engineering to promote the lives of his people by bringing Technology to the region. His hobbies are reading books of wisdom, listing to Qur’an, and playing football.</p>`,
  },
  {
    name: "Achuil Akol Kueth",
    bio: `<p>My name's Achuil Akol Kueth from South Sudan  and civil war forced me to seek for asylum  refugee here in Kenya. I have been in Kakuma for 9 years till I completed my primary level & High level here in the camp. </p>

    <p>Our families members were six in numbers where I was the third born child in my family  as  two were older than me and one was younger . Due to very long civil war in Sudan  it has caused me to lost my  parents include my siblings  . And for now ,  i may say I'm living with my cousins,   and luckily UN became my second parents which  can give me  food and shelter. </p>

    <p>Since I completed my High School I have been able to volunteered in delivered my services to the community by teaching my fellows  students,  participating in community works,  and run small business to cater for my needs as well.</p>

    <p>I would like to pursue in civil engineering as career because  I have passion in designing infrastructures and maintain  constructions , and buildings.With courage  and confident I have in me will make me to keeps my dreams ,  hard work ,  and patient alive.</p>

    <p>We are here to give back to our people and,  I believed one day I will come up with design that would be like beautiful  Parish's Tower  in my country South sudan.</p>

   <p> My hobbies are; Swimming,  travelling ,  and reading as well .</p>
   `,
  },
  {
    name: "Aguel Chol Malual",
    bio: `<p>My name is Aguel Chol Malual I was born in kakuma refugee camp, but my family is from South Sudan. I am the second oldest in a family of six children and currently live my mom as I lost my dad some years back. I am passionate about helping people because I was lucky to have my uncles who helped us out and so I would like to do the same for others. I would like to study Radiology as there are few people in this field that can help my community back in South Sudan. I  am really inspired by BTS because they are really hard working and make me believe that through hard work I can achieve my set goals. My hobbies are singing, dancing, and travelling.</p>`,
  },
  {
    name: "Amou Chol Malual",
    bio: `<p>My name is Amou Chol. I am the first born in a family of six children,three girls three boys. I am a south sudanese who have never been to the country. I was born in kakuma Refugee camp. My parents fled from the war in south Sudan back in 1991. They walked long journeys before coming to kakuma. They were hungry,cold ,tired ,and sun was often too hot during day time and the fact they were bare footed made the situation unbearable.I am currently volunteering as a teacher at kakuma Refugee secondary school. I lost my father in 2018. This took a toll on me emotionally and financially. My studies was threatened but my uncle came in and helped my family. Am passionate about humanity and hope to see it thrive everyday. My hobbies are playing basketball and reading.</p>`,
  },
  {
    name: "Andrew Pajok Maluk",
    bio: `<p>Am Andrew Pajok Maluk, second born of seven children of Maluk's family. I’m South Sudanese by nationality. I made it to Kakuma Refugee camp in Feb 2006 after my father had come here for medication and met my uncle who had fled to Kakuma during the Bor Massacre in 1991.</p>

    <p>During the repatriation we went to Nakuru where I did my academics till class seven but my uncle could not meet all the needs required so we returned to Kakuma.The same year my elder sister got married and her husband took me to a boarding school till my graduation and that was my highest education as I was concern then I came to   to stay with my aunt.</p>

    <p>My passion is to be a software engineer and advance my knowledge in developing a humanoid robot. I was inspired by Hanson company in Hong Kong when they developed Sofia.

    Being in a third world country accessing higher education is by chance and this is one of the challenges that is going to kill my dream.

    I do love playing basketball and football, and listening to music in my free time.</p>`,
  },
  {
    name: "Bahome Seraphin Bahome",
    bio: `<p>My name is Bahome Seraphin Bahome a CongoIese by nationality, Refugee under UNHCR currently living in kakuma Refugee camp which is located in Kenya. I have been in the camp for ten years since 2010. I left my country Congo for various reasons and the main reason is political instability in the country. the situation was worsen when the Eastern part of the  country where I lived was invaded by Rebels. The rebels did a lot of evils things such as Raping women, kidnaping people and killing the innocent Congolese. This situation forced my family to migrate here in Kakuma Refugee camp. Reaching in the camp I faced many challenges, one of the challenge was the education system of kenya, which was  different from that of Congo as the language of instruction was English unlike Congo where French was used in the school, I have overcome this challenge by commiting myself in studying of English  at long last I was able to understand the language very well when I was in class seven primary. Iam someone who is very passionate about civil engineering, I would like to become an engineer in future so that I can go back to my country and improve the infrastructural development. Someone who inspired me is Albert eisten, his commitment and success mean a lot to me, I would like to be like him one day, I like one of his quote that say "the power of our imagination is greater than the power of our intellect." I really adore this person since he achieved a lot. My hobbies are writing, reading novels, traveling and listening to the music.</p>`,
  },
  {
    name: "Grace Amer Bech",
    bio: `<p>My name is Grace Amer Bech. I am a 22yrs old South Sudanese girl living in Kakuma Refugee Camp. I came to Kakuma in 2007 after a series of brutal wars in South Sudan. Before coming to Kakuma, I was taken to a cattle camp, both for safety and food. The long duration of wars combined with, drought and famine caused great starvation and people saw the cattle as the only survival thing. The cattle camp, wasn’t again safe and therefore, my uncle who was partially educated, took I and my elder sister to live with his family in Kakuma. We left my mother and my other siblings since the journey was long and the cost was high. I have since then lived with my uncle’s family for fourteen years in Kakuma. Being the second child in a family of seven has taught me independence and this is how I survived the long separation from my family. I attended school in urban Kenya through a number of financial aids from well- wishers and my uncle.  During my sophomore year of high school, another coup attempt happened in South Sudan, and this caused massive loss of lives, properties and other essential valuables. My family got displaced and went to NYUMAZI REFUGEE camp in NORTHERN UGANDA where they’re now refugees. My well- wishers were also affected by this and therefore, I had to drop out due to lack of school fees. I sought help from friends who had similar problems and were able to attend school through sports. I solely sought the scholarship and they admitted me without even the basics such as school uniform. I felt that, going back to school was a great effort on my side even if I had to repeat a year. I had solved this great challenge. I am currently a high school graduate, with no access to further education and I spend my time volunteering in church and teaching at a high school when I visit my family.  Reaching this level, is as a result of all the people that have lend me a helping hand in my whole life. This inspires me to be a medical practitioner as there’s no greater proffession that will enable me serve human kind as this. Through this, I will be able to address health issues back at home.  I am passionate about serving humanity since I have only received great acts of kindness from people. My hobbies are, reading, listening to music, playing volleyball and visiting places like orphanages.</p>`,
  },
  {
    name: "John Makol Chuol Deng",
    bio: `<p>My name is John Makol Chuol Deng .I was born in South Sudan specifically in a place called Awatau which is a small village in central Bhar el Ghazal. Both my parents are south Sudanese that makes me south Sudanese by birth.   I am the firstborn in a family of seven. My dad was a soldier who I didn't see a lot. At age  12 my dad was killed, so I was left with my mum and siblings. I came to Kakuma on January 22nd of 2012, however, in 2014 I was lucky to get a Kenya family friend who took me to Eldoret one of the towns here in Kenya for part of my primary education. Kakuma is a very challenging place to live. First of all the place extremely hot, sanitation is very poor and we are exposed to several diseases especially on days that it rains. However, at least we have peace here compared to our country where gunshots are the routine. Something that has inspired me is seeing the kids here in Kakuma having a strong desire to compete nationally despite the harsh environment. I really want to do computer science because I am fascinated by technology because  I believe this can be a chance for me to help my fellow refugee kids. It is my dream that when I completed my degree to come back to Kakuma and South Sudan to give them better education through technology.</p>`,
  },
  {
    name: "Kuany Atem Kuany",
    bio: `<p>My name is Kuany Atem. A south sudanese refugee living in kakuma refugee camp. Kakuma has been my home all my life as I was born and grew up here in the camp. My parents fled a civil war in south sudan during the Sudanese civil war and they arrived in the camp in 1992. My mother was fled to find a safer place for her then six children but she unfortunately lost all them to malnutrition. She came to the camp empty handed .she came to give birth to me here in the camp after years of persuasion by the elders .she names me kuany meaning suffering but later gave me another name ,adhiei ,which means blessing. I opened her eyes to the endless blessings of God as she would always say.</p>

    <p>I started schooling here in the camp and because of my good performance, an organization named seeds of south sudan offered to educate me in a better school outside the camp. i finished in 2018 and became a volunteer teacher at kakuma refugee secondary school. I would like to persue a degree in computer science .i believe with technology one can solve world challenges ranging from health, agriculture, education, and global warming. I am passionate to bring live changing innovations to my community in the health sector so that no more child will succumb to malnutrition and other treatable diseases.</p>

    <p>In my free time I love reading writing essays and playing basketball.</p>`,
  },
  {
    name: "Rhoda Akon Juach",
    bio: `<p>My name is Juach Rhoda Akon,a South Sudanese by nationality and from South Sudan.I am the first born out of five children,raised by a single mother,from an extended family.My mother,siblings and I moved into Kakuma Camp on twenty ninth,January,2002 ;the same year we were registered as refugees.We have been living in the camp, roughly twenty years down the line.Since the day I came into the camp,I have faced a lot of challenges such as:inadequate food,money to buy basic needs such as clothing,harsh weather conditions and external attacks from the host community.All in all,I congratulate myself for having overcome these struggles and hardships.My role model is my own mother.This is the only person who will stretch beyond her limits in order to safeguard her children.It is her genuine love and sacrifice that inspires me to work harder in order to come to the rescue of other neglected children.Some of my interests include;music,writing and literacy.Furthermore,I am very passionate about giving back positively to my society,a society which has brought me up in an upright way.My hobbies include;taking part in charity work,reading novels.listening to music and dancing.If given a chance to pursue further my education, my interests include;Bachelor of music.Literacy,International Relations and Law.I would like to take any of the above courses because they will give me a higher chance of changing people's mindsets,views and negative opinions.</p>`,
  },
  {
    name: "Riak Awany Mayar",
    bio: `<p>My name is Riak Awany Mayar, South Sudanese by nationality , and I am the first in the family of six children. I was born in South Sudan and my family is currently in South Sudan. I have been living in Kakuma refugee camp since 2012 . I had fled from the country because I was forced to join the military at teenage age to serve as a soldier but with help of my father he organised for me to come to kakuma refugees camp in Kenya for better education.I have been inspired by Nelson Mandela since I do remember one of his sayings, that education is the powerful  weapons to eradicate the problem. I believed through education I would transform my community in terms of offering better services . I have been faced with a lot of challenges despite education being offered free from primary to secondary . Lack of support has been a great challenge to me. I'm inspired to major in pharmacy so that I can assist my community from further being affected by a number of diseases that are always curable. In my country, there are numerous diseases that require doctors whose help is required to supply medications to the citizens therefore, I feel like pursuing pharmacy to restore the remnants.I'm currently teaching in Somalia Bantu secondary school as a teacher being employed under Windle trust of Kenya as incentive. I teach mathematics and chemistry in Somalia Bantu. My hobbies are; reading novels, engaging in community activities such as serving as leader and I also like listening to music. Furthermore, I do offer assistance in teaching child girls during holidays to keep the girls busy.</p>`,
  },
  {
    name: "Susan Amin Lual",
    bio: `<p>My name is Susan Amin Lual. I am a South Sudanese by nationality. When war broke out in 2013, we fled to Kakuma Refugee Camp in 2014 for safety and education. I am a second born to a family of 12. I teach as a volunteer over the holiday to primary kids who might need help in anything. My mother inspires me because even in the face of adversities, she stays strong and bold. Even though she is illiterate she works herself tirelessly to make sure we go to school, with her concerned nature it promotes my sisters and I to grow. Throughout my education I have had my own ups and downs, because my society does not allow girls to be educated but I did not give up on schooling. I would like to study Public Health, because I want many people in South Sudan neglected to be paid attention to. There are many diseases which are affecting and killing people in South Sudan and with this more hospitals and medicines are needed and I would like to teach people to be aware of how to avoid getting infected from certain diseases. I am passionate about helping the sick people in my country, that is South Sudan, most of them are not aware of certain diseases that are affecting them and they need to be educated on this. My hobbies are reading novels, travelling and listening to music.</p>`,
  },
];
