module.exports = [
  {
    name: "Abdirizak Aden Mohamed",
    bio: `<p>Abdirizak Aden Mohamed is the sixth born of 12 children. He was born in Ethiopia where he lived until nine. His family lived in a rural area of the Warder region in Ethiopia where they reared small livestock. One night, he was forced to flee his home country when a war between the government of Ethiopia and the so-called ONLF group suddenly broke out. Every member of his family had to flee for his/her life, for there was no time to plan or regroup to escape. There is no information up to date about the livestock, perhaps they were taken by either group. After some days of looking for each other, the family was able to reunite.</p>

    <p>They started their journey for a better life which led them to Dadaab Refugee Camp and later resettled to Kakuma Refugee Camp by the UNHCR, The United Nations High Commission for Refugees. He enrolled in Somali Bantu Primary School, and then to newly built Lokitaung primary school. He later went to Vision Secondary School within Kakuma. He has been in Kakuma for twelve years. During that time, he volunteered teaching at Vision secondary school, then in Greenlight Secondary School before he was accepted into Elimisha Kakuma.
    Aden hopes to pursue Computer and Electrical Engineering to promote the lives of his people by bringing technology to the region. His hobbies are reading books of wisdom, listening to the Quran, and playing football.</p>`,
  },
  {
    name: "Achuil Akol Kueth",
    bio: `<p>My name's Achuil Akol Kueth from South Sudan and the civil war forced me to seek asylum as a refugee in Kenya. I have been in Kakuma for 9 years where I completed my primary and secondary education.</p>

    <p>I was the third born child in my family of four siblings, and we lived with my parents in South Sudan.  Due to the very long civil war in Sudan, I lost my parents and my siblings. For now, I may say I'm living with my cousins, and luckily the UN became my second parents, who can give me food and shelter. </p>

    <p>Since I completed high school, I have volunteered and delivered my services to the community by teaching my fellow students, participating in community works, and running small businesses to cater for my needs as well.</p>

    <p>My hobbies are swimming, travelling, and reading as well. I would like to pursue civil engineering as a career because I have passion for designing infrastructure and constructing buildings. With courage and confidence, I believe I have the will to keep my dreams alive. </p>

    <p>We are here to give back to our people, and I believe one day I will come up with a design that would contribute to the infrastructure in South Sudan.</p>
   `,
  },
  {
    name: "Aguel Chol Malual",
    bio: `<p>My name is Aguel Chol Malual.  I was born in Kakuma Refugee Camp, but my family is from South Sudan. I am the second oldest in a family of six children and currently live with my mom, as I lost my dad some years back. I am passionate about helping people because I was lucky to have my uncles who helped us out, and so I would like to do the same for others. I would like to study Radiology as there are few people in this field that can help my community back in South Sudan. I am really inspired by BTS, the K-pop band, because they are really hard working and make me believe that through hard work I can achieve my set goals. My hobbies are singing, dancing, and travelling.</p>`,
  },
  {
    name: "Amou Chol Malual",
    bio: `<p>My name is Amou Chol. I am the first born in a family of six children made up of three girls and three boys. I am South Sudanese by nationality, but I have never been there. I was born in Kakuma Refugee Camp. My parents fled from the war in South Sudan back in 1991.  They walked long journeys before arriving in Kakuma. WHen they arrived, they were barefoot, having survived extreme temperatures walking across the desert, hungry, cold, and tired.  I am currently volunteering as a teacher at Kakuma Refugee secondary school. I lost my father in 2018, which took a toll on me emotionally and financially. My studies were threatened, but my uncle came in and helped my family. I am passionate about humanity and hope to see it thrive everyday. My hobbies are playing basketball and reading.</p>`,
  },
  {
    name: "Andrew Pajok Maluk",
    bio: `<p>My name is Andrew Pajok Maluk, and I am the second born of seven children. I’m South Sudanese by nationality. I made it to Kakuma Refugee camp in February 2006 after my father had come here for medication and met my uncle who had fled to Kakuma during the Bor Massacre in 1991.</p>

    <p>During the repatriation we went to Nakuru where I did my academics till class seven, but my uncle could not meet all the needs required so we returned to Kakuma.The same year my elder sister got married and her husband took me to a boarding school till my graduation.</p>

    <p>My passion is to be a software engineer and advance my knowledge in developing a humanoid robot. I was inspired by Hanson company in Hong Kong when they developed Sofia. Being in a developing country and being a refugee creates many barriers to accessing higher education, which present challenges that could obstruct my dream. I love playing basketball and football and listening to music in my free time.</p>`,
  },
  {
    name: "Bahome Seraphin Bahome",
    bio: `<p>Bahome Seraphin Bahome is the first-born child in a family of nine children. He is from the Democratic Republic of Congo (DRC), and he is a refugee under the United Nations High Commission for Refugees (UNHCR). He is currently living in the Kakuma Refugee Camp, located in the northern part of Kenya. Bahome has been in the camp for ten years since 2010. He left his country Congo for various reasons, mainly political instability in the country. The situation worsened when the Eastern part of the country where he lived was invaded by Rebels. The rebels did a lot of evil things such as raping women, kidnaping people, killing the innocent Congolese, and attacking the students in schools. This situation forced his family to flee here to Kakuma Refugee Camp. Reaching the camp, he faced many challenges, one of which was the education system of Kenya, which was different from that of Congo, as the language of instruction was English instead of French, like in the DRC. He has overcome this challenge by committing himself to study English. He volunteered to teach mathematics and chemistry at Greenlight Secondary School for one year before joining Elimisha Kakuma.  He is very passionate about civil engineering, and he would like to become an engineer in the future so that he can go back to his country and improve the infrastructure. Someone who inspired him is Albert Einstein, who was also a refugee. His commitment and success mean a lot to him, and he would like to be like him one day. One of his most powerful quotes for Bahome is, "the power of our imagination is greater than the power of our intellect." Bahome’s hobbies are writing, reading novels, traveling, and listening to music.</p>`,
  },
  {
    name: "Grace Amer Bech",
    bio: `<p>My name is Grace Amer Bech. I am a South Sudanese girl living in Kakuma Refugee Camp. In the year 2007, after a series of brutal wars, my sister and I left our family in South Sudan to come to Kakuma Refugee Camp with my uncle to access education and safety. The rest of my family later resettled in Nyumanzi Refugee Resettlement Camp in Northern Uganda in the year 2014 after another civil war erupted in 2013. During my sophomore year of high school, another coup attempt happened in South Sudan, which caused massive loss of lives, properties, and other essential valuables. I had to drop out of school since my uncle was left bankrupt in the aftermath. With my inborn grit, I managed to overcome this challenge and pursued my education. I sought help from friends who had similar problems and I was able to attend school through sports. I got a football scholarship, through which I managed to graduate from high school with good grades. My resilience and determination have always been evident throughout my academic journey.</p>

    <p>Being the second born and away from my family, I have learned independence and self-drive through taking care of her younger siblings and later my cousins.  The help that I have received throughout my academic journey has inspired me to be a community person. I am awed by the works the United Nations has done and continues to do for refugees worldwide. My admiration has led me to have a long list of volunteer activities, such as teaching in both Kakuma Refugee Camp and Nyumanzi Refugee Resettlement Camp, working in the clinic as a translator and attendee, and volunteering at church service and through community cleaning. In all aspects of life I always strive to make a change.</p>

    <p>I am currently undecided about the exact career to pursue in college, but am interested in health, international relations, and global studies. I love reading novels, chatting with friends, playing volleyball, and swimming. </p>`,
  },
  {
    name: "John Makol Chuol Deng",
    bio: `<p>My name is Makol Deng. I was born in South Sudan, in a  small village in central Bahr el Ghazal. Both my parents were South Sudanese. My dad was a soldier whom I rarely saw. I was barely 10 years old when he was killed. Due to domestic family problems, I lived with my grandmother for most of my early childhood. Growing up she has always taught me to be industrious, committed to whatever I started, to be resilient  and to always believe in myself.  She always spoke with utmost kindness. My main job was to take care of her animals in the village. After what felt like forever of war, I decided to seek refuge in Kenya’s Kakuma Refugee Camp. I arrived on January 22nd of 2012.</p>

    <p> Kakuma Refugee Camp is a very challenging place to live. It is extremely hot, sanitation is very poor and we are exposed to many diseases especially on days that it rains. Something that has inspired me is seeing the kids here in Kakuma having a strong desire to compete nationally in academics despite the harsh environment.</p>

    <p>In 2014, I was lucky to be sponsored by a Kenyan family friend in Eldoret. This family changed my life as they paid for the rest of my primary school fees and supported my first term in high school. Although I later got a scholarship, it was their immeasurable kindness that opened other opportunities for me. This kindness changed me completely because through them I was able to access a quality education. They are my heroes and role models of what I dream to achieve in life.</p>

    <p>Although I have not yet figured out the best career to pursue, my interests range from computer science, to pharmacy and environmental engineering. Each of these three means one thing to me: to change the situation of my community and country at large. Acquiring skills in these multidisciplinary combinations of subjects will allow me to solve complex problems. I have always dreamed of providing a better education, building health facilities, and providing clean water to my community.</p>

    <p>Going to university means acquiring the skills and tools that I will use to change the situation in my community.</p>

    <p>Growing up in my community, I know what it means to learn under a tree and lack resources like books and teachers. I know what it means to be sick and not get treatment because there is no hospital. What it means to suffer from water-bones disease because of lack of clean water.</p>
    `,
  },
  {
    name: "Kuany Atem Kuany",
    bio: `<p>My name is Kuany Atem. I am a South Sudanese refugee living in Kakuma Refugee Camp. Kakuma has been my home all my life as I was born and grew up here in the camp. My parents fled a civil war in South Sudan during the Sudanese civil war and they arrived in the camp in 1992. My mother fled to find a safer place for her then six children but she unfortunately lost all of them to malnutrition. She came to the camp empty handed.  She came to give birth to me here in the camp after years of persuasion by the elders.  She named me Kuany meaning suffering but later gave me another name, Adhiei, which means blessing. She would always say I opened her eyes to the endless blessings of God. </p>

    <p>I started schooling here in the camp and because of my good performance, an organization named Seeds of South Sudan offered to educate me in a better school outside the camp. I finished in 2018 and became a volunteer teacher at Kakuma Refugee Secondary School. I would like to pursue a degree in computer science.  I believe with technology one can solve world challenges ranging from healthcare, agriculture, education, and global warming. I am passionate about bringing life changing innovations to my community in the health sector so that no more children will succumb to malnutrition and other treatable diseases.</p>

    <p>In my free time I love reading, writing essays, and playing basketball.</p>`,
  },
  {
    name: "Rhoda Akon Juach",
    bio: `<p>My name is Juach Rhoda Akon, a South Sudanese by nationality and from South Sudan. I am the first born out of five children,raised by a single mother,from an extended family.  My mother,siblings and I moved into Kakuma Camp on the 29th of January, 2002-- the same year we were registered as refugees.  We have been living in the camp, roughly twenty years.  Since the day I came into the camp, I have faced a lot of challenges such as inadequate food, lack of money to buy basic needs such as clothing, harsh weather conditions and external attacks from the host community.  All in all, I congratulate myself for having overcome these struggles and hardships.  My role model is my own mother.  This is the only person who will stretch beyond her limits in order to safeguard her children.  It is her genuine love and sacrifice that inspires me to work harder in order to come to the rescue of other neglected children.  Some of my interests include music, writing and literacy.  Furthermore, I am very passionate about giving back positively to my society, a society which has brought me up in an upright way.  My hobbies include taking part in charity work, reading novels, listening to music, and dancing.  If given a chance to pursue further education, my interests include earning a Bachelors of Arts in music,International Relations or Law.  I would like to take on any of the above majors  because they will give me a higher chance of changing people's mindsets, views and negative opinions.</p>`,
  },
  {
    name: "Riak Awany Mayar",
    bio: `<p>My name is Riak Awany Mayar, I am South Sudanese by nationality, and I am the first in the family of six children. I was born in South Sudan and my family is still currently in South Sudan. I have been living in Kakuma refugee camp since 2012. I had fled from the country because I was forced to join the military as a young teenager to serve as a soldier, but after I escaped and with the help of my father, he organised for me to come to Kakuma Refugee Camp in Kenya for better education.  I have been inspired by Nelson Mandela from one of his sayings, that education is the powerful weapon to change the world. I believe through education I can transform my community in terms of offering better services. I have been faced with a lot of challenges; despite education being offered “free” from primary to secondary, there are many associated costs like uniforms, school materials, and books.  Lack of support has been a great challenge to me. I'm inspired to major in pharmacy so that I can assist my community from further being affected by a number of curable diseases. In my country, there are numerous diseases that require doctors to supply medications, and yet there are no pharmacies and few healthcare options for citizens; therefore, I’d like to pursue pharmacy to prevent needless deaths.  I'm currently teaching mathematics and chemistry in Somali Bantu Secondary School as an ‘incentive’ worker in Kakuma Refugee Camp. I also teach girls during school holidays as the rate of girls finishing primary and secondary is much lower than that of their male peers.  My hobbies are reading novels, engaging in community service, and listening to music. </p>`,
  },
  {
    name: "Susan Amin Lual",
    bio: `<p>My name is Susan Amin Lual. I am a South Sudanese by nationality. When war broke out in 2013, we eventually fled to Kakuma Refugee Camp in 2014 for safety and education. I am a second born in a family of 12. I teach as a volunteer over the holiday to primary school students who might need help in anything. My mother inspires me because even in the face of adversities, she stays strong and bold. Even though she is illiterate, she works herself tirelessly to make sure we go to school.  With her concerned nature, it encourages my sisters and I to grow personally and academically. Throughout my education I have had my own ups and downs, because my society does not allow girls to be educated, but I did not give up on schooling. I would like to study Public Health, because I want many people in South Sudan who are neglected to be paid attention to. There are many diseases which are affecting and killing people in South Sudan and because of this, more hospitals and medicines are needed.  I am passionate about helping the sick people in my home country of South Sudan.  Most of them are not aware of certain diseases that are affecting them and they need to be educated on this. My hobbies are reading novels, travelling, and listening to music.</p>`,
  },
];
